### ISSUE TITLE
Create RU file

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/RTMP-server#1]

**Comment by IvLaptev** [comment]
@CAPCHIK, написал. Если всё ок, закрывай.

**Comment by CAPCHIK** [comment]
Утром поправлю, и закрою

**Comment by CAPCHIK** [comment]
Сделано в b9512511420ce06661710fbad5457dd078e01a1c и 97b167bdb197f0c534efb3c329c794df40911866
